### ISSUE TITLE
Safari extension?

### ISSUE THREAD

**Issue by benadamstyles** [kentcdodds/genies-lamp#5]
Since updating my mac to macOS, I have been using Safari a lot more. It's a little zippier than Chrome and doesn't appear to use as much memory. But I dearly miss Genie's Lamp when I'm using Safari.

Do you have any plans to make this a Safari extension too? I would be very happy to help out if you are interested in the idea.

**Comment by kentcdodds** [comment]
I had no idea people were still using the extension! I'm glad you like it. I have no plans of working on the extension at all. But I'd be happy to hand the project off to someone who would be willing to maintain it!

**Comment by benadamstyles** [comment]
I'll look into what's involved and see if I can fit it in. I'll be back in touch after a little research!
